name: Auto Label PRs
on:
  pull_request:
    types:
      - opened

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['temp: port to doc6']
            });
